# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giow/Downloads/Development/20191-team-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giow/Downloads/Development/20191-team-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/giow/Documents/clion-2019.1.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giow/Downloads/Development/20191-team-2/CMakeFiles /home/giow/Downloads/Development/20191-team-2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giow/Downloads/Development/20191-team-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BombermanC++

# Build rule for target.
BombermanC++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BombermanC++
.PHONY : BombermanC++

# fast build rule for target.
BombermanC++/fast:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/build
.PHONY : BombermanC++/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f tests/libs/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make tests/libs/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f tests/libs/googletest/googlemock/CMakeFiles/gmock.dir/build.make tests/libs/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/libs/googletest/googletest/CMakeFiles/gtest_main.dir/build.make tests/libs/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/libs/googletest/googletest/CMakeFiles/gtest.dir/build.make tests/libs/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Block.o: src/Block.cpp.o

.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/Bomber.o: src/Bomber.cpp.o

.PHONY : src/Bomber.o

# target to build an object file
src/Bomber.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Bomber.cpp.o
.PHONY : src/Bomber.cpp.o

src/Bomber.i: src/Bomber.cpp.i

.PHONY : src/Bomber.i

# target to preprocess a source file
src/Bomber.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Bomber.cpp.i
.PHONY : src/Bomber.cpp.i

src/Bomber.s: src/Bomber.cpp.s

.PHONY : src/Bomber.s

# target to generate assembly for a file
src/Bomber.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Bomber.cpp.s
.PHONY : src/Bomber.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameBoard.o: src/GameBoard.cpp.o

.PHONY : src/GameBoard.o

# target to build an object file
src/GameBoard.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameBoard.cpp.o
.PHONY : src/GameBoard.cpp.o

src/GameBoard.i: src/GameBoard.cpp.i

.PHONY : src/GameBoard.i

# target to preprocess a source file
src/GameBoard.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameBoard.cpp.i
.PHONY : src/GameBoard.cpp.i

src/GameBoard.s: src/GameBoard.cpp.s

.PHONY : src/GameBoard.s

# target to generate assembly for a file
src/GameBoard.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameBoard.cpp.s
.PHONY : src/GameBoard.cpp.s

src/GameLogic.o: src/GameLogic.cpp.o

.PHONY : src/GameLogic.o

# target to build an object file
src/GameLogic.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameLogic.cpp.o
.PHONY : src/GameLogic.cpp.o

src/GameLogic.i: src/GameLogic.cpp.i

.PHONY : src/GameLogic.i

# target to preprocess a source file
src/GameLogic.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameLogic.cpp.i
.PHONY : src/GameLogic.cpp.i

src/GameLogic.s: src/GameLogic.cpp.s

.PHONY : src/GameLogic.s

# target to generate assembly for a file
src/GameLogic.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameLogic.cpp.s
.PHONY : src/GameLogic.cpp.s

src/GameObjectSDL.o: src/GameObjectSDL.cpp.o

.PHONY : src/GameObjectSDL.o

# target to build an object file
src/GameObjectSDL.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameObjectSDL.cpp.o
.PHONY : src/GameObjectSDL.cpp.o

src/GameObjectSDL.i: src/GameObjectSDL.cpp.i

.PHONY : src/GameObjectSDL.i

# target to preprocess a source file
src/GameObjectSDL.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameObjectSDL.cpp.i
.PHONY : src/GameObjectSDL.cpp.i

src/GameObjectSDL.s: src/GameObjectSDL.cpp.s

.PHONY : src/GameObjectSDL.s

# target to generate assembly for a file
src/GameObjectSDL.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/GameObjectSDL.cpp.s
.PHONY : src/GameObjectSDL.cpp.s

src/Matrix.o: src/Matrix.cpp.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/PlayerObjLogic.o: src/PlayerObjLogic.cpp.o

.PHONY : src/PlayerObjLogic.o

# target to build an object file
src/PlayerObjLogic.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/PlayerObjLogic.cpp.o
.PHONY : src/PlayerObjLogic.cpp.o

src/PlayerObjLogic.i: src/PlayerObjLogic.cpp.i

.PHONY : src/PlayerObjLogic.i

# target to preprocess a source file
src/PlayerObjLogic.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/PlayerObjLogic.cpp.i
.PHONY : src/PlayerObjLogic.cpp.i

src/PlayerObjLogic.s: src/PlayerObjLogic.cpp.s

.PHONY : src/PlayerObjLogic.s

# target to generate assembly for a file
src/PlayerObjLogic.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/PlayerObjLogic.cpp.s
.PHONY : src/PlayerObjLogic.cpp.s

src/TextureManager.o: src/TextureManager.cpp.o

.PHONY : src/TextureManager.o

# target to build an object file
src/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/TextureManager.cpp.o
.PHONY : src/TextureManager.cpp.o

src/TextureManager.i: src/TextureManager.cpp.i

.PHONY : src/TextureManager.i

# target to preprocess a source file
src/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/TextureManager.cpp.i
.PHONY : src/TextureManager.cpp.i

src/TextureManager.s: src/TextureManager.cpp.s

.PHONY : src/TextureManager.s

# target to generate assembly for a file
src/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/TextureManager.cpp.s
.PHONY : src/TextureManager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/BomberTests.o: tests/BomberTests.cpp.o

.PHONY : tests/BomberTests.o

# target to build an object file
tests/BomberTests.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/BomberTests.cpp.o
.PHONY : tests/BomberTests.cpp.o

tests/BomberTests.i: tests/BomberTests.cpp.i

.PHONY : tests/BomberTests.i

# target to preprocess a source file
tests/BomberTests.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/BomberTests.cpp.i
.PHONY : tests/BomberTests.cpp.i

tests/BomberTests.s: tests/BomberTests.cpp.s

.PHONY : tests/BomberTests.s

# target to generate assembly for a file
tests/BomberTests.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/BomberTests.cpp.s
.PHONY : tests/BomberTests.cpp.s

tests/MatrixTests.o: tests/MatrixTests.cpp.o

.PHONY : tests/MatrixTests.o

# target to build an object file
tests/MatrixTests.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/MatrixTests.cpp.o
.PHONY : tests/MatrixTests.cpp.o

tests/MatrixTests.i: tests/MatrixTests.cpp.i

.PHONY : tests/MatrixTests.i

# target to preprocess a source file
tests/MatrixTests.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/MatrixTests.cpp.i
.PHONY : tests/MatrixTests.cpp.i

tests/MatrixTests.s: tests/MatrixTests.cpp.s

.PHONY : tests/MatrixTests.s

# target to generate assembly for a file
tests/MatrixTests.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/MatrixTests.cpp.s
.PHONY : tests/MatrixTests.cpp.s

tests/PositionTests.o: tests/PositionTests.cpp.o

.PHONY : tests/PositionTests.o

# target to build an object file
tests/PositionTests.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/PositionTests.cpp.o
.PHONY : tests/PositionTests.cpp.o

tests/PositionTests.i: tests/PositionTests.cpp.i

.PHONY : tests/PositionTests.i

# target to preprocess a source file
tests/PositionTests.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/PositionTests.cpp.i
.PHONY : tests/PositionTests.cpp.i

tests/PositionTests.s: tests/PositionTests.cpp.s

.PHONY : tests/PositionTests.s

# target to generate assembly for a file
tests/PositionTests.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/PositionTests.cpp.s
.PHONY : tests/PositionTests.cpp.s

tests/TextureManagerTests.o: tests/TextureManagerTests.cpp.o

.PHONY : tests/TextureManagerTests.o

# target to build an object file
tests/TextureManagerTests.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/TextureManagerTests.cpp.o
.PHONY : tests/TextureManagerTests.cpp.o

tests/TextureManagerTests.i: tests/TextureManagerTests.cpp.i

.PHONY : tests/TextureManagerTests.i

# target to preprocess a source file
tests/TextureManagerTests.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/TextureManagerTests.cpp.i
.PHONY : tests/TextureManagerTests.cpp.i

tests/TextureManagerTests.s: tests/TextureManagerTests.cpp.s

.PHONY : tests/TextureManagerTests.s

# target to generate assembly for a file
tests/TextureManagerTests.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/TextureManagerTests.cpp.s
.PHONY : tests/TextureManagerTests.cpp.s

tests/tests.o: tests/tests.cpp.o

.PHONY : tests/tests.o

# target to build an object file
tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/tests.cpp.o
.PHONY : tests/tests.cpp.o

tests/tests.i: tests/tests.cpp.i

.PHONY : tests/tests.i

# target to preprocess a source file
tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/tests.cpp.i
.PHONY : tests/tests.cpp.i

tests/tests.s: tests/tests.cpp.s

.PHONY : tests/tests.s

# target to generate assembly for a file
tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/BombermanC++.dir/build.make CMakeFiles/BombermanC++.dir/tests/tests.cpp.s
.PHONY : tests/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... BombermanC++"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/Bomber.o"
	@echo "... src/Bomber.i"
	@echo "... src/Bomber.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameBoard.o"
	@echo "... src/GameBoard.i"
	@echo "... src/GameBoard.s"
	@echo "... src/GameLogic.o"
	@echo "... src/GameLogic.i"
	@echo "... src/GameLogic.s"
	@echo "... src/GameObjectSDL.o"
	@echo "... src/GameObjectSDL.i"
	@echo "... src/GameObjectSDL.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/PlayerObjLogic.o"
	@echo "... src/PlayerObjLogic.i"
	@echo "... src/PlayerObjLogic.s"
	@echo "... src/TextureManager.o"
	@echo "... src/TextureManager.i"
	@echo "... src/TextureManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/BomberTests.o"
	@echo "... tests/BomberTests.i"
	@echo "... tests/BomberTests.s"
	@echo "... tests/MatrixTests.o"
	@echo "... tests/MatrixTests.i"
	@echo "... tests/MatrixTests.s"
	@echo "... tests/PositionTests.o"
	@echo "... tests/PositionTests.i"
	@echo "... tests/PositionTests.s"
	@echo "... tests/TextureManagerTests.o"
	@echo "... tests/TextureManagerTests.i"
	@echo "... tests/TextureManagerTests.s"
	@echo "... tests/tests.o"
	@echo "... tests/tests.i"
	@echo "... tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

